services:
  bigdl-workflow:
    command:
      - /usr/bin/bash
      - -c
      - |
        echo "Download dataset 'ml-100k'"
        rm -f ml-100k.zip
        rm -rf ml-100k
        wget https://files.grouplens.org/datasets/movielens/ml-100k.zip
        unzip ml-100k.zip
        echo "Install required packages"
        source activate bigdl
        pip install tensorflow==2.9.0
        echo "Start distributed training"
        python tf_train_spark_dataframe.py --dataset ml-100k
        echo "Start distributed inference"
        python tf_predict_spark_dataframe.py --dataset ml-100k
    environment: 
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    image: intelanalytics/bigdl-orca:latest
    privileged: true
    volumes: 
      - $PWD:/workspace
    working_dir: /workspace/python/orca/tutorial/NCF
