name: 'Run Orca Python Horovod Tf2 Py37 Spark3'
description: 'Run Orca Python Horovod Tf2 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        sudo dpkg --configure -a
        sudo apt-get update
        sudo apt-get install wget

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Setup env
      shell: bash -l {0}
      run: |
        if [ -d "/opt/conda/envs/py37" ];then
          rm -rf /opt/conda/envs/py37
        fi
        conda create -n py37 -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        conda info --env
        # source activate py37
        
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip install pytest
        
        
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
