name: 'Run Orca Python Py38 Spark3'
description: 'Run Orca Python Py38 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash -l {0}
      run: |
        # source activate py38
        export SPARK_LOCAL_HOSTNAME=localhost
        
        # unit test test_inference_model requires "app.properties"
        # bash python/dev/release_default_linux_spark3.sh default false false false -Ddata-store-url=$HTTP_URI -U
        
        pip install -i https://pypi.python.org/simple --pre --upgrade bigdl-orca-spark3

        pip install torch==1.7.1
        pip install torchvision==0.8.2
        pip install torchmetrics==0.10.0
        # pip install tensorflow==2.9.0
        pip install pyarrow==4.0.1
        pip install pandas==1.1.5
        pip install h5py==2.10.0	

        chmod a+x python/orca/dev/test/run-pytests-spark.sh
        python/orca/dev/test/run-pytests-spark.sh
        # source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
