name: 'Run Orca Tutorial Xshards Py37 Spark3'
description: 'Run Orca Tutorial Xshards Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Setup Env
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get install wget

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4
        
    - name: Run Test
      shell: bash -l {0}
      run: |
        # conda remove -n orca-tutorial-xshards-py37 -y --all
        # conda create -n orca-tutorial-xshards-py37 -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        # conda info -e
        # source activate orca-tutorial-xshards-py37

        export SPARK_LOCAL_HOSTNAME=localhost6
        # bash python/dev/release_default_linux_spark3.sh default false false false -Ddata-store-url=$HTTP_URI -U
        
        # install dllib
        # pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl

        # install orca
        # pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl

        pip install --pre --upgrade bigdl-orca-spark3[ray]
        pip install tensorflow==1.15.0
        pip install pandas
        pip install cloudpickle
        pip install scikit-learn==0.22.2.post1
        pip install torchvision
        pip install pyarrow==4.0.1
        pip install jep==3.9.0
        pip install grpcio==1.43.0
        
        pip install pytest
        
        export SPARK_LOCAL_HOSTNAME=localhost
        export FTP_URI=${FTP_URI}
        chmod a+x python/orca/dev/test/run-tutorial-xshards.sh
        python/orca/dev/test/run-tutorial-xshards.sh

        source deactivate
        conda remove -n orca-tutorial-xshards-py37 -y --all
      env:
        BIGDL_ROOT: ${{ github.workspace }}
