name: 'Run Orca Python Py37 Pytorch'
description: 'Run Orca Python Pytorch'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        
        bash python/dev/release_default_linux_spark313.sh default false false false -Ddata-store-url=$HTTP_URI -U
        
        # install dllib
        pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl
        # install orca
        pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl
     
        pip install tensorflow==2.9.0
        pip list
        chmod a+x python/orca/dev/test/run-pytests-tf2.sh
        python/orca/dev/test/run-pytests-tf2.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}